# JWT 签发密钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
# JWT Token 过期时间
expiration: 1000h

mysql:
  addr: 127.0.0.1:3306
  username: fastgo
  password: fastgo1234
  database: fastgo
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 10s

log:
  format: text
  level: info
  output: stdout
